export const events = [
     {
      id: 1,
      eventName: "Sleepless night",
      eventType: "negative",
      eventOccurrence: "evening",
      eventDescription: "You are facing harsh consequences of total lack of sleep last night..",
      eventEffect1: "sleep - 1, health - 1",
      score: 4,     
      health: -1,
      sleep: -1,
      skills: 0,
      motivation: 0,
      luck: 0
    },
     {
      id: 2,
      eventName: "Mind blur",
      eventType: "negative",
      eventOccurrence: "morning",
      eventDescription: "You have lost some focus and some of your knowledge dissapeared",
      eventEffect1: " skills - 1",
      score: 4,
      health: 0,
      sleep: 0,
      skills: -1,
      motivation: 0,
      luck: 0
    },
     {
      id: 3,
      eventName: "An accident",
      eventType: "negative",
      eventOccurrence: "evening",
      eventDescription: "You just had ann accident that caused some health damage",
      eventEffect1: " health - 2",
      score: 4,
      health: -2,
      sleep: 0,
      skills: 0,
      motivation: 0,
      luck: 0
    },
    {
      id: 4,
      eventName: "Bad luck",
      eventType: "negative",
      eventOccurrence: "evening",
      eventDescription: "You have become less lucky out of nowhere",
      eventEffect1: " luck - 1",
      score: 4,
      health: 0,
      sleep: 0,
      skills: 0,
      motivation: 0,
      luck: -1
    },
     {
      id: 5,
      eventName: "Toxic meeting",
      eventType: "negative",
      eventOccurrence: "evening",
      eventDescription: "you have met very negative person, luckily it did not last any longer, your motivation drops",
      eventEffect1: " motivation - 1",
      score: 4,
      health: 0,
      sleep: 0,
      skills: 0,
      motivation: -1,
      luck: 0
    },
     {
      id: 6,
      eventName: "Loss of resources",
      eventType: "negative",
      eventOccurrence: "evening",
      eventDescription: "you just have lost some money, you have no clue how it happened",
      eventEffect1: " points - 30",
      score: -30,
      health: 0,
      sleep: 0,
      skills: 0,
      motivation: 0,
      luck: 0
    },
     {
      id: 7,
      eventName: "Extra skills",
      eventType: "positive",
      eventOccurrence: "morning",
      eventDescription: "You have found very interesting link with knowledge that just fits your goal..",
      eventEffect1: " skills + 1",
      score: 8,
      health: 0,
      sleep: 0,
      skills: 1,
      motivation: 0,
      luck: 0
    },
    {
      id: 8,
      eventName: "Relax at SPA",
      eventType: "positive",
      eventOccurrence: "evening",
      eventDescription: "You have visited spa, that took care of tiredness and fatigue a bit.",
      eventEffect1: " sen + 1, health + 1",
      score: 8,
      health: 1,
      sleep: 1,
      skills: 0,
      motivation: 0,
      luck: 0
    },
    {
      id: 9,
      eventName: "Good luck",
      eventType: "positive",
      eventOccurrence: "evening",
      eventDescription: "You have become more lucky.",
      eventEffect1: " luck + 1",
      score: 4,
      health: 0,
      sleep: 0,
      skills: 0,
      motivation: 0,
      luck: 1
    },
    {
      id: 10,
      eventName: "Clear mind",
      eventType: "positive",
      eventOccurrence: "evening",
      eventDescription: "You managed to let go of some intrusive thoughts, now you can focus more on your goals.",
      eventEffect1: " motivation + 1",
      score: 4,
      health: 0,
      sleep: 0,
      skills: 0,
      motivation: 1,
      luck: 0
    },
    {
      id: 11,
      eventName: "Extra resources",
      eventType: "positive",
      eventOccurrence: "evening",
      eventDescription: "You have found nice amount of money, that was unexpected! Happy days!",
      eventEffect1: " points + 30",
      score: 30,
      health: 0,
      sleep: 0,
      skills: 0,
      motivation: 0,
      luck: 0
    }]
